[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "encoder_demo"
version = "0.1.0"
description = "A demo project with cipher plugins"
authors = [
  { name="Your Name", email="your.email@example.com" }
]
